# Generated by Django 4.2.3 on 2023-07-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
