# Generated by Django 4.2.3 on 2023-07-14 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_lote', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('barrio', models.CharField(max_length=50)),
                ('dirrecion', models.CharField(max_length=50)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Comprador_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_facturacion', models.DateField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.comprador')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
    ]
