# Generated by Django 4.2.3 on 2023-07-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_producto_ubicacion_comprador_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(choices=[('CEDULA', 'Documento Nacional de Identidad'), ('PASAPORTE', 'Pasaporte')], max_length=50)),
                ('cedula', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.persona')),
            ],
        ),
        migrations.RemoveField(
            model_name='comprador_producto',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='comprador_producto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='comprador',
        ),
        migrations.DeleteModel(
            name='Comprador',
        ),
        migrations.DeleteModel(
            name='Comprador_Producto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
